packages:
  - "services/*"

catalog:
  "@aztec/accounts": "4.0.0-devnet.2-patch.1"
  "@aztec/aztec.js": "4.0.0-devnet.2-patch.1"
  "@aztec/foundation": "4.0.0-devnet.2-patch.1"
  "@aztec/kv-store": "4.0.0-devnet.2-patch.1"
  "@aztec/stdlib": "4.0.0-devnet.2-patch.1"
  fastify: "^4.28.0"
  viem: "^2.18.0"
  yaml: "^2.4.5"
  zod: "^3.23.8"
  "@types/node": "^20.0.0"
  tsx: "^4.0.0"
  typescript: "^5.4.0"
