accepted_asset_name: "humanUSDC"
market_rate_num: 1
market_rate_den: 1000
fee_bips: 200
port: 3000
quote_validity_seconds: 300
quote_auth_mode: "disabled"
quote_rate_limit_enabled: true
quote_rate_limit_max_requests: 60
quote_rate_limit_window_seconds: 60
quote_rate_limit_max_tracked_keys: 10000
fpc_address: "0x244fd9caaea2e4ca4800e3877a3cf984b5c15dbeef0b3dd3aa25ae51a7c44f76"
accepted_asset_address: "0x1b6a3479389c0890b5b5c12fb8c2c5e415d02b7be653d37a2296c64b6f3a31bf"
