accepted_asset_name: "FpcAcceptedAsset"
market_rate_num: 1
market_rate_den: 1000
fee_bips: 200
port: 3000
quote_validity_seconds: 300
quote_auth_mode: "disabled"
quote_rate_limit_enabled: true
quote_rate_limit_max_requests: 60
quote_rate_limit_window_seconds: 60
quote_rate_limit_max_tracked_keys: 10000
fpc_address: "0x1be2cae678e1eddd712682948119b3fe2c3ff3f381d78ebea06162f21487d60f"
accepted_asset_address: "0x07348d12aae72d1c2ff67cb2bf6b0e54f2ac39484f21cad7247d4e27b4822afb"
