
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import CounterContractArtifactJson from './artifacts/mock_counter-Counter.json' with { type: 'json' };
export const CounterContractArtifact = loadContractArtifact(CounterContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract Counter;
 */
export class CounterContract extends ContractBase {
  
  protected constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, CounterContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): CounterContract {
    return Contract.at(address, CounterContract.artifact, wallet) as CounterContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, headstart: (bigint | number), owner: AztecAddressLike) {
    return new DeployMethod<CounterContract>(PublicKeys.default(), wallet, CounterContractArtifact, (instance, wallet) => CounterContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, headstart: (bigint | number), owner: AztecAddressLike) {
    return new DeployMethod<CounterContract>(publicKeys, wallet, CounterContractArtifact, (instance, wallet) => CounterContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof CounterContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<CounterContract['methods'][M]>
  ) {
    return new DeployMethod<CounterContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      CounterContractArtifact,
      (instance, wallet) => CounterContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return CounterContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(CounterContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'counters'> {
      return {
        counters: {
      slot: new Fr(1n),
    }
      } as ContractStorageLayout<'counters'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** __emit_public_init_nullifier() */
    __emit_public_init_nullifier: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** _always_revert_public() */
    _always_revert_public: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** always_revert() */
    always_revert: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_counter(owner: struct) */
    get_counter: ((owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** increment(owner: struct) */
    increment: ((owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** initialize(headstart: integer, owner: struct) */
    initialize: ((headstart: (bigint | number), owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
